; Generated by labs/011_goal_language_to_asm_net_proxy/src/generate_asm.py
; Goal source: labs/011_goal_language_to_asm_net_proxy/src/goal.lang
; Program source: labs/011_goal_language_to_asm_net_proxy/src/program.lang
; Goal: C64NET PROXY PING
; Priority: runtime speed first; teaching clarity is secondary.
; Output: assembly app source. No main.c is generated or consumed.
; Network pattern: C64 RS232/Hayes stream -> host proxy/server -> internet-facing work.
; This app opens KERNAL RS232 device 2, sends AT/Hayes text, sends a line request, then reads one response line.
.import __EXEHDR__
.export _main

SCREEN_RAM = $0400
COLOR_RAM = $d800
SPACE_CHAR = $20
BORDER_COLOR = $d020
BACKGROUND_COLOR = $d021
SETLFS = $ffba
SETNAM = $ffbd
OPEN = $ffc0
CLOSE = $ffc3
CHKIN = $ffc6
CHKOUT = $ffc9
CLRCHN = $ffcc
CHRIN = $ffcf
CHROUT = $ffd2
RS232_LFN = $02
RS232_DEVICE = $02
RESPONSE_SCREEN = SCREEN_RAM+602
RESPONSE_MAX = 36
SCREEN_PTR_LO = $fb
SCREEN_PTR_HI = $fc
TEXT_PTR_LO = $fd
TEXT_PTR_HI = $fe

.segment "STARTUP"
_main:
    lda #$06
    sta BORDER_COLOR
    lda #$00
    sta BACKGROUND_COLOR
    ; exact 1000-byte clear: four 250-byte stripes, no overlap
    ldy #250
fast_clear_loop_01:
    lda #SPACE_CHAR
    sta SCREEN_RAM-1,y
    sta SCREEN_RAM+249,y
    sta SCREEN_RAM+499,y
    sta SCREEN_RAM+749,y
    lda #$00
    sta COLOR_RAM-1,y
    sta COLOR_RAM+249,y
    sta COLOR_RAM+499,y
    sta COLOR_RAM+749,y
    dey
    bne fast_clear_loop_01

    lda #$03
    sta SCREEN_RAM+82
    lda #$36
    sta SCREEN_RAM+83
    lda #$34
    sta SCREEN_RAM+84
    lda #$0e
    sta SCREEN_RAM+85
    lda #$05
    sta SCREEN_RAM+86
    lda #$14
    sta SCREEN_RAM+87
    lda #$20
    sta SCREEN_RAM+88
    lda #$10
    sta SCREEN_RAM+89
    lda #$12
    sta SCREEN_RAM+90
    lda #$0f
    sta SCREEN_RAM+91
    lda #$18
    sta SCREEN_RAM+92
    lda #$19
    sta SCREEN_RAM+93
    lda #$20
    sta SCREEN_RAM+94
    lda #$10
    sta SCREEN_RAM+95
    lda #$09
    sta SCREEN_RAM+96
    lda #$0e
    sta SCREEN_RAM+97
    lda #$07
    sta SCREEN_RAM+98
    lda #$0c
    sta SCREEN_RAM+202
    lda #$01
    sta SCREEN_RAM+203
    lda #$0e
    sta SCREEN_RAM+204
    lda #$07
    sta SCREEN_RAM+205
    lda #$15
    sta SCREEN_RAM+206
    lda #$01
    sta SCREEN_RAM+207
    lda #$07
    sta SCREEN_RAM+208
    lda #$05
    sta SCREEN_RAM+209
    lda #$20
    sta SCREEN_RAM+210
    lda #$07
    sta SCREEN_RAM+211
    lda #$05
    sta SCREEN_RAM+212
    lda #$0e
    sta SCREEN_RAM+213
    lda #$05
    sta SCREEN_RAM+214
    lda #$12
    sta SCREEN_RAM+215
    lda #$01
    sta SCREEN_RAM+216
    lda #$14
    sta SCREEN_RAM+217
    lda #$05
    sta SCREEN_RAM+218
    lda #$04
    sta SCREEN_RAM+219
    lda #$20
    sta SCREEN_RAM+220
    lda #$01
    sta SCREEN_RAM+221
    lda #$13
    sta SCREEN_RAM+222
    lda #$0d
    sta SCREEN_RAM+223
    lda #$0e
    sta SCREEN_RAM+282
    lda #$0f
    sta SCREEN_RAM+283
    lda #$20
    sta SCREEN_RAM+284
    lda #$0d
    sta SCREEN_RAM+285
    lda #$01
    sta SCREEN_RAM+286
    lda #$09
    sta SCREEN_RAM+287
    lda #$0e
    sta SCREEN_RAM+288
    lda #$2e
    sta SCREEN_RAM+289
    lda #$03
    sta SCREEN_RAM+290
    lda #$12
    sta SCREEN_RAM+362
    lda #$13
    sta SCREEN_RAM+363
    lda #$32
    sta SCREEN_RAM+364
    lda #$33
    sta SCREEN_RAM+365
    lda #$32
    sta SCREEN_RAM+366
    lda #$20
    sta SCREEN_RAM+367
    lda #$0d
    sta SCREEN_RAM+368
    lda #$0f
    sta SCREEN_RAM+369
    lda #$04
    sta SCREEN_RAM+370
    lda #$05
    sta SCREEN_RAM+371
    lda #$0d
    sta SCREEN_RAM+372
    lda #$20
    sta SCREEN_RAM+373
    lda #$10
    sta SCREEN_RAM+374
    lda #$12
    sta SCREEN_RAM+375
    lda #$0f
    sta SCREEN_RAM+376
    lda #$18
    sta SCREEN_RAM+377
    lda #$19
    sta SCREEN_RAM+378
    lda #$13
    sta SCREEN_RAM+442
    lda #$05
    sta SCREEN_RAM+443
    lda #$0e
    sta SCREEN_RAM+444
    lda #$04
    sta SCREEN_RAM+445
    lda #$09
    sta SCREEN_RAM+446
    lda #$0e
    sta SCREEN_RAM+447
    lda #$07
    sta SCREEN_RAM+448
    lda #$20
    sta SCREEN_RAM+449
    lda #$07
    sta SCREEN_RAM+450
    lda #$05
    sta SCREEN_RAM+451
    lda #$14
    sta SCREEN_RAM+452
    lda #$20
    sta SCREEN_RAM+453
    lda #$2f
    sta SCREEN_RAM+454
    lda #$03
    sta SCREEN_RAM+455
    lda #$36
    sta SCREEN_RAM+456
    lda #$34
    sta SCREEN_RAM+457
    lda #$2f
    sta SCREEN_RAM+458
    lda #$10
    sta SCREEN_RAM+459
    lda #$09
    sta SCREEN_RAM+460
    lda #$0e
    sta SCREEN_RAM+461
    lda #$07
    sta SCREEN_RAM+462
    lda #$12
    sta SCREEN_RAM+562
    lda #$05
    sta SCREEN_RAM+563
    lda #$13
    sta SCREEN_RAM+564
    lda #$10
    sta SCREEN_RAM+565
    lda #$0f
    sta SCREEN_RAM+566
    lda #$0e
    sta SCREEN_RAM+567
    lda #$13
    sta SCREEN_RAM+568
    lda #$05
    sta SCREEN_RAM+569
    lda #$3a
    sta SCREEN_RAM+570

    jsr open_rs232_01
    jsr send_at_01
    jsr read_response_01
    jsr send_dial_01
    jsr read_response_01
    jsr send_request_01
    jsr read_response_01

hold_forever_01:
    jmp hold_forever_01

open_rs232_01:
    lda #RS232_LFN
    ldx #RS232_DEVICE
    ldy #$00
    jsr SETLFS
    lda #$02
    ldx #<rs232_control_name
    ldy #>rs232_control_name
    jsr SETNAM
    jsr OPEN
    rts

send_at_01:
    lda #<at_command
    sta TEXT_PTR_LO
    lda #>at_command
    sta TEXT_PTR_HI
    jmp send_rs232_zstring_01

send_dial_01:
    lda #<dial_command
    sta TEXT_PTR_LO
    lda #>dial_command
    sta TEXT_PTR_HI
    jmp send_rs232_zstring_01

send_request_01:
    lda #<request_command
    sta TEXT_PTR_LO
    lda #>request_command
    sta TEXT_PTR_HI
    jmp send_rs232_zstring_01

send_rs232_zstring_01:
    ldx #RS232_LFN
    jsr CHKOUT
    ldy #$00
send_rs232_loop_01:
    lda (TEXT_PTR_LO),y
    beq send_rs232_done_01
    jsr CHROUT
    iny
    bne send_rs232_loop_01
send_rs232_done_01:
    jsr CLRCHN
    rts

read_response_01:
    lda #<RESPONSE_SCREEN
    sta SCREEN_PTR_LO
    lda #>RESPONSE_SCREEN
    sta SCREEN_PTR_HI
    ; clear previous response field
    ldy #$00
clear_response_loop_01:
    lda #SPACE_CHAR
    sta (SCREEN_PTR_LO),y
    iny
    cpy #RESPONSE_MAX
    bcc clear_response_loop_01
    ldx #RS232_LFN
    jsr CHKIN
    ldy #$00
read_response_loop_01:
    jsr CHRIN
    cmp #$0d
    beq read_response_done_01
    cmp #$0a
    beq read_response_loop_01
    jsr ascii_to_screen_01
    sta (SCREEN_PTR_LO),y
    iny
    cpy #RESPONSE_MAX
    bcc read_response_loop_01
read_response_done_01:
    jsr CLRCHN
    rts

ascii_to_screen_01:
    cmp #$41
    bcc ascii_not_upper_01
    cmp #$5b
    bcs ascii_not_upper_01
    sec
    sbc #$40
    rts
ascii_not_upper_01:
    cmp #$61
    bcc ascii_keep_01
    cmp #$7b
    bcs ascii_keep_01
    sec
    sbc #$60
    rts
ascii_keep_01:
    rts

    ; TEXT_PTR_LO/TEXT_PTR_HI are zero-page scratch constants.
    ; They must not be allocated as normal CODE labels because (zp),y addressing is zero-page only.

rs232_control_name:
    ; KERNAL RS232 open control bytes matching the classic OPEN 2,2,0,CHR$(8)+CHR$(1) pattern.
    .byte $08, $01
at_command:
    ; AT
    .byte $41, $54, $0d, $00
dial_command:
    ; ATDT127.0.0.1:6464
    .byte $41, $54, $44, $54, $31, $32, $37, $2e, $30, $2e, $30, $2e, $31, $3a, $36, $34, $36, $34, $0d, $00
request_command:
    ; GET /c64/ping
    .byte $47, $45, $54, $20, $2f, $63, $36, $34, $2f, $70, $69, $6e, $67, $0d, $00

.segment "INIT"
.segment "ONCE"
.segment "CODE"
