#!/usr/bin/env python3
"""Generate ca65-compatible C64 assembly from a tiny fail-closed language. Unknown commands must fail closed."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

COLOR = {
    "black": 0,
    "white": 1,
    "red": 2,
    "cyan": 3,
    "purple": 4,
    "green": 5,
    "blue": 6,
    "yellow": 7,
    "orange": 8,
    "brown": 9,
    "light red": 10,
    "dark gray": 11,
    "gray": 12,
    "light green": 13,
    "light blue": 14,
    "light gray": 15,
}

PUT_RE = re.compile(r'^put "([A-Z0-9 $\-!.?]+)" at row ([0-9]{1,2}) col ([0-9]{1,2}) color ([a-z ]+)$')


def screen_code(ch: str) -> int:
    if "A" <= ch <= "Z":
        return ord(ch) - ord("A") + 1
    if "0" <= ch <= "9":
        return ord(ch)
    table = {
        " ": 32,
        "$": 36,
        "-": 45,
        "!": 33,
        ".": 46,
        "?": 63,
    }
    if ch in table:
        return table[ch]
    raise ValueError(f"unsupported character {ch!r}")


def parse_line(line: str, line_no: int) -> dict:
    raw = line.strip()
    if not raw or raw.startswith("#"):
        return {"op": "comment", "line": line_no, "source": line.rstrip("\n")}
    if raw == "clear screen":
        return {"op": "clear_screen", "line": line_no, "source": raw}
    if raw == "wait forever":
        return {"op": "wait_forever", "line": line_no, "source": raw}
    if raw == "wait for key":
        return {"op": "wait_for_key", "line": line_no, "source": raw}
    for prefix, op, register in [
        ("set border ", "set_border", "$d020"),
        ("set background ", "set_background", "$d021"),
    ]:
        if raw.startswith(prefix):
            color_name = raw[len(prefix):]
            if color_name not in COLOR:
                raise ValueError(f"line {line_no}: unsupported color {color_name!r}")
            return {
                "op": op,
                "line": line_no,
                "source": raw,
                "color": color_name,
                "value": COLOR[color_name],
                "register": register,
            }
    match = PUT_RE.match(raw)
    if match:
        text, row_s, col_s, color_name = match.groups()
        row = int(row_s)
        col = int(col_s)
        if color_name not in COLOR:
            raise ValueError(f"line {line_no}: unsupported color {color_name!r}")
        if row < 0 or row > 24:
            raise ValueError(f"line {line_no}: row out of range {row}")
        if col < 0 or col > 39:
            raise ValueError(f"line {line_no}: column out of range {col}")
        if col + len(text) > 40:
            raise ValueError(f"line {line_no}: text extends beyond row")
        return {
            "op": "put_text",
            "line": line_no,
            "source": raw,
            "text": text,
            "row": row,
            "col": col,
            "offset": row * 40 + col,
            "color": color_name,
            "color_value": COLOR[color_name],
            "screen_codes": [screen_code(ch) for ch in text],
        }
    raise ValueError(f"line {line_no}: unknown command {raw!r}")


def parse_program(text: str) -> list[dict]:
    return [parse_line(line, n) for n, line in enumerate(text.splitlines(), start=1)]


def hexbyte(value: int) -> str:
    return f"${value:02x}"


def hexword(value: int) -> str:
    return f"${value:04x}"


def emit_asm(intents: list[dict]) -> str:
    lines: list[str] = [
        "; Generated by labs/009_language_to_asm/src/generate_asm.py",
        "; Source: labs/009_language_to_asm/src/program.lang",
        "; ca65/cl65 C64 program shape: import BASIC SYS header and provide required runtime segments.",
        ".import __EXEHDR__",
        ".export _main",
        "",
        '.segment "STARTUP"',
        "_main:",
    ]
    for intent in intents:
        op = intent["op"]
        if op == "comment":
            continue
        lines.append(f"    ; line {intent['line']}: {intent['source']}")
        if op in {"set_border", "set_background"}:
            lines.extend([
                f"    lda #{hexbyte(intent['value'])}",
                f"    sta {intent['register']}",
            ])
        elif op == "clear_screen":
            lines.extend([
                "    ldx #$00",
                "clear_loop:",
                "    lda #$20",
                "    sta $0400,x",
                "    sta $0500,x",
                "    sta $0600,x",
                "    sta $06e8,x",
                "    lda #$0e",
                "    sta $d800,x",
                "    sta $d900,x",
                "    sta $da00,x",
                "    sta $dae8,x",
                "    inx",
                "    bne clear_loop",
            ])
        elif op == "put_text":
            start = intent["offset"]
            for idx, code in enumerate(intent["screen_codes"]):
                lines.extend([
                    f"    lda #{hexbyte(code)}",
                    f"    sta {hexword(0x0400 + start + idx)}",
                    f"    lda #{hexbyte(intent['color_value'])}",
                    f"    sta {hexword(0xD800 + start + idx)}",
                ])
        elif op == "wait_forever":
            lines.extend([
                "hold_forever:",
                "    jmp hold_forever",
            ])
        elif op == "wait_for_key":
            lines.extend([
                "wait_key:",
                "    jsr $ffe4",
                "    beq wait_key",
                "hold_after_key:",
                "    jmp hold_after_key",
            ])
        else:
            raise ValueError(f"cannot emit op {op!r}")
        lines.append("")
    lines.extend([
        "",
        '.segment "INIT"',
        '.segment "ONCE"',
        '.segment "CODE"',
    ])
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print("usage: generate_asm.py program.lang generated_intent.json generated.s", file=sys.stderr)
        return 2
    lang_path = Path(argv[1])
    intent_path = Path(argv[2])
    asm_path = Path(argv[3])
    intents = parse_program(lang_path.read_text())
    intent_path.write_text(json.dumps(intents, indent=2) + "\n")
    asm_path.write_text(emit_asm(intents))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
