; Generated by labs/009_language_to_asm/src/generate_asm.py
; Source: labs/009_language_to_asm/src/program.lang
; ca65/cl65 C64 program shape: import BASIC SYS header and provide required runtime segments.
.import __EXEHDR__
.export _main

.segment "STARTUP"
_main:
    ; line 1: set border blue
    lda #$06
    sta $d020

    ; line 2: set background black
    lda #$00
    sta $d021

    ; line 3: clear screen
    ldx #$00
clear_loop:
    lda #$20
    sta $0400,x
    sta $0500,x
    sta $0600,x
    sta $06e8,x
    lda #$0e
    sta $d800,x
    sta $d900,x
    sta $da00,x
    sta $dae8,x
    inx
    bne clear_loop

    ; line 4: put "LANGUAGE TO ASM" at row 10 col 5 color yellow
    lda #$0c
    sta $0595
    lda #$07
    sta $d995
    lda #$01
    sta $0596
    lda #$07
    sta $d996
    lda #$0e
    sta $0597
    lda #$07
    sta $d997
    lda #$07
    sta $0598
    lda #$07
    sta $d998
    lda #$15
    sta $0599
    lda #$07
    sta $d999
    lda #$01
    sta $059a
    lda #$07
    sta $d99a
    lda #$07
    sta $059b
    lda #$07
    sta $d99b
    lda #$05
    sta $059c
    lda #$07
    sta $d99c
    lda #$20
    sta $059d
    lda #$07
    sta $d99d
    lda #$14
    sta $059e
    lda #$07
    sta $d99e
    lda #$0f
    sta $059f
    lda #$07
    sta $d99f
    lda #$20
    sta $05a0
    lda #$07
    sta $d9a0
    lda #$01
    sta $05a1
    lda #$07
    sta $d9a1
    lda #$13
    sta $05a2
    lda #$07
    sta $d9a2
    lda #$0d
    sta $05a3
    lda #$07
    sta $d9a3

    ; line 5: put "GENERATED 6502" at row 12 col 7 color light green
    lda #$07
    sta $05e7
    lda #$0d
    sta $d9e7
    lda #$05
    sta $05e8
    lda #$0d
    sta $d9e8
    lda #$0e
    sta $05e9
    lda #$0d
    sta $d9e9
    lda #$05
    sta $05ea
    lda #$0d
    sta $d9ea
    lda #$12
    sta $05eb
    lda #$0d
    sta $d9eb
    lda #$01
    sta $05ec
    lda #$0d
    sta $d9ec
    lda #$14
    sta $05ed
    lda #$0d
    sta $d9ed
    lda #$05
    sta $05ee
    lda #$0d
    sta $d9ee
    lda #$04
    sta $05ef
    lda #$0d
    sta $d9ef
    lda #$20
    sta $05f0
    lda #$0d
    sta $d9f0
    lda #$36
    sta $05f1
    lda #$0d
    sta $d9f1
    lda #$35
    sta $05f2
    lda #$0d
    sta $d9f2
    lda #$30
    sta $05f3
    lda #$0d
    sta $d9f3
    lda #$32
    sta $05f4
    lda #$0d
    sta $d9f4

    ; line 6: wait forever
hold_forever:
    jmp hold_forever


.segment "INIT"
.segment "ONCE"
.segment "CODE"
