; Generated by Lab 010 generate_asm.py.
; Milestone F.2: buffered-turn Pac-Man with visible dot and energizer scoring from verified board.txt.
; Generated assembly is an artifact, not the board authority.

.setcpu "6502"

SCREEN_BASE = $0400
COLOR_BASE = $d800
BOARD_WIDTH = 28
BOARD_HEIGHT = 22
BOARD_CHAR_LEFT = 6
BOARD_CHAR_TOP = 1
DOT_COUNT = 205
POWER_DOT_COUNT = 4
WALL_COUNT = 332
CUSTOM_CHAR_COUNT = 19
CUSTOM_CHARSET_BYTES = 152
CUSTOM_CHARSET_ADDR = $3000
SPRITE_DATA_BYTES = 512
SPRITE_DATA_ADDR = $3400
SPRITE_PTR_E_OPEN = $d0
SPRITE_PTR_W_OPEN = $d1
SPRITE_PTR_N_OPEN = $d2
SPRITE_PTR_S_OPEN = $d3
SPRITE_PTR_E_CLOSED = $d4
SPRITE_PTR_W_CLOSED = $d5
SPRITE_PTR_N_CLOSED = $d6
SPRITE_PTR_S_CLOSED = $d7
START_CELL_X = $0d
START_CELL_Y = $0d
START_TARGET_CELL_X = $0e
START_TARGET_CELL_Y = $0d
START_SPRITE_X_LO = $a9
START_SPRITE_X_HI = $00
START_SPRITE_Y = $9c
START_TARGET_SPRITE_X_LO = $b1
START_TARGET_SPRITE_X_HI = $00
START_TARGET_SPRITE_Y = $9c
START_DIR_PTR = $d0
JOY_PORT_2 = $dc00
JOY_UP = $01
JOY_DOWN = $02
JOY_LEFT = $04
JOY_RIGHT = $08
KEYBOARD_ROW_PORT = $dc00
KEYBOARD_COL_PORT = $dc01
KEY_ROW_ALL = $ff
KEY_ROW_1 = $fd
KEY_ROW_2 = $fb
KEY_W = $02
KEY_A = $04
KEY_S = $20
KEY_D = $04
MASK_UP = $01
MASK_DOWN = $02
MASK_LEFT = $04
MASK_RIGHT = $08
BOARD_PTR = $f7
COLOR_PTR = $f9
SCREEN_PTR = $fb
LEGAL_PTR = $fd

.segment "LOADADDR"

; PRG file load address. C64 PRG files must begin with the little-endian
; address where the following bytes should be loaded.
.word $0801

.segment "EXEHDR"

; BASIC autostart line:
; 10 SYS 2061
;
; With the standard C64 load address at $0801, this header ends at $080d.
; Decimal 2061 is $080d, the first byte of the CODE segment below.
.word basic_line_end
.word 10
.byte $9e, $32, $30, $36, $31, $00
basic_line_end:
.word $0000

.segment "CODE"

start:
    sei
    lda #$00
    sta $d020
    sta $d021
    jsr install_custom_charset
    jsr install_sprite_data
    lda #$1c
    sta $d018
    jsr clear_screen
    jsr render_board
    jsr init_score
    jsr init_sprite
    jsr init_pacman_state

main_loop:
    jsr delay_frame
    jsr read_input_buffer
    jsr read_keyboard_fallback
    jsr at_target
    beq moving
    jsr commit_target_cell
    jsr choose_next_target_from_buffer
    jsr update_sprite_registers
    jmp main_loop

moving:
    jsr update_mouth_animation
    jsr set_sprite_pointer_current
    jsr move_sprite_toward_target
    jsr update_sprite_registers
    jmp main_loop

delay_frame:
    ldx #$02
wait_frame:
    lda $d012
wait_raster_low:
    cmp $d012
    beq wait_raster_low
wait_next_frame:
    lda $d012
    bne wait_next_frame
    dex
    bne wait_frame
    rts

init_sprite:
    lda #$01
    sta $d015
    lda #$00
    sta $d017
    sta $d01d
    sta $d01c
    sta $d01b
    lda #$07
    sta $d027
    rts

init_pacman_state:
    lda #START_CELL_X
    sta pac_cell_x
    lda #START_TARGET_CELL_X
    sta target_cell_x
    lda #START_CELL_Y
    sta pac_cell_y
    lda #START_TARGET_CELL_Y
    sta target_cell_y
    lda #START_SPRITE_X_LO
    sta sprite_x_lo
    lda #START_TARGET_SPRITE_X_LO
    sta target_x_lo
    lda #START_SPRITE_X_HI
    sta sprite_x_hi
    lda #START_TARGET_SPRITE_X_HI
    sta target_x_hi
    lda #START_SPRITE_Y
    sta sprite_y
    lda #START_TARGET_SPRITE_Y
    sta target_y
    lda #START_DIR_PTR
    sta target_dir_ptr
    sta requested_dir_ptr
    lda #$00
    sta mouth_counter
    sta mouth_phase
    jsr set_sprite_pointer_current
    jsr update_sprite_registers
    rts

commit_target_cell:
    lda target_cell_x
    sta pac_cell_x
    lda target_cell_y
    sta pac_cell_y
    jsr erase_current_cell
    rts

init_score:
    lda #$30
    ldx #$00
init_score_loop:
    sta score_digits,x
    inx
    cpx #$06
    bne init_score_loop
    jsr render_score
    rts

render_score:
    lda #$13
    sta $0401
    lda #$03
    sta $0402
    lda #$0f
    sta $0403
    lda #$12
    sta $0404
    lda #$05
    sta $0405
    lda #$20
    sta $0406
    ldx #$00
render_score_digit_loop:
    lda score_digits,x
    sta $0407,x
    inx
    cpx #$06
    bne render_score_digit_loop
    rts

add_score_10:
    jsr score_increment_tens
    jsr render_score
    rts

add_score_50:
    jsr score_increment_tens
    jsr score_increment_tens
    jsr score_increment_tens
    jsr score_increment_tens
    jsr score_increment_tens
    jsr render_score
    rts

score_increment_tens:
    ldx #$04
score_increment_digit:
    inc score_digits,x
    lda score_digits,x
    cmp #$3a
    bne score_increment_done
    lda #$30
    sta score_digits,x
    dex
    bpl score_increment_digit
score_increment_done:
    rts

read_input_buffer:
    lda JOY_PORT_2
    sta joystick_state

    lda joystick_state
    and #JOY_LEFT
    beq buffer_left

    lda joystick_state
    and #JOY_RIGHT
    beq buffer_right

    lda joystick_state
    and #JOY_UP
    beq buffer_up

    lda joystick_state
    and #JOY_DOWN
    beq buffer_down

    rts

buffer_left:
    lda #SPRITE_PTR_W_OPEN
    sta requested_dir_ptr
    rts

buffer_right:
    lda #SPRITE_PTR_E_OPEN
    sta requested_dir_ptr
    rts

buffer_up:
    lda #SPRITE_PTR_N_OPEN
    sta requested_dir_ptr
    rts

buffer_down:
    lda #SPRITE_PTR_S_OPEN
    sta requested_dir_ptr
    rts

read_keyboard_fallback:
    lda #KEY_ROW_1
    sta KEYBOARD_ROW_PORT
    lda KEYBOARD_COL_PORT
    sta keyboard_row_state

    lda keyboard_row_state
    and #KEY_W
    beq keyboard_buffer_up

    lda keyboard_row_state
    and #KEY_A
    beq keyboard_buffer_left

    lda keyboard_row_state
    and #KEY_S
    beq keyboard_buffer_down

    lda #KEY_ROW_2
    sta KEYBOARD_ROW_PORT
    lda KEYBOARD_COL_PORT
    sta keyboard_row_state

    lda keyboard_row_state
    and #KEY_D
    beq keyboard_buffer_right

    lda #KEY_ROW_ALL
    sta KEYBOARD_ROW_PORT
    rts

keyboard_buffer_up:
    lda #SPRITE_PTR_N_OPEN
    sta requested_dir_ptr
    lda #KEY_ROW_ALL
    sta KEYBOARD_ROW_PORT
    rts

keyboard_buffer_left:
    lda #SPRITE_PTR_W_OPEN
    sta requested_dir_ptr
    lda #KEY_ROW_ALL
    sta KEYBOARD_ROW_PORT
    rts

keyboard_buffer_down:
    lda #SPRITE_PTR_S_OPEN
    sta requested_dir_ptr
    lda #KEY_ROW_ALL
    sta KEYBOARD_ROW_PORT
    rts

keyboard_buffer_right:
    lda #SPRITE_PTR_E_OPEN
    sta requested_dir_ptr
    lda #KEY_ROW_ALL
    sta KEYBOARD_ROW_PORT
    rts

choose_next_target_from_buffer:
    lda requested_dir_ptr
    cmp #SPRITE_PTR_W_OPEN
    beq try_requested_left
    cmp #SPRITE_PTR_E_OPEN
    beq try_requested_right
    cmp #SPRITE_PTR_N_OPEN
    beq try_requested_up
    cmp #SPRITE_PTR_S_OPEN
    beq try_requested_down
    jmp continue_current_direction

try_requested_left:
    jsr load_legal_mask
    and #MASK_LEFT
    beq continue_current_direction
    lda pac_cell_x
    sec
    sbc #$01
    sta target_cell_x
    lda pac_cell_y
    sta target_cell_y
    lda #SPRITE_PTR_W_OPEN
    sta target_dir_ptr
    jsr set_target_sprite_from_cell
    rts

try_requested_right:
    jsr load_legal_mask
    and #MASK_RIGHT
    beq continue_current_direction
    lda pac_cell_x
    clc
    adc #$01
    sta target_cell_x
    lda pac_cell_y
    sta target_cell_y
    lda #SPRITE_PTR_E_OPEN
    sta target_dir_ptr
    jsr set_target_sprite_from_cell
    rts

try_requested_up:
    jsr load_legal_mask
    and #MASK_UP
    beq continue_current_direction
    lda pac_cell_x
    sta target_cell_x
    lda pac_cell_y
    sec
    sbc #$01
    sta target_cell_y
    lda #SPRITE_PTR_N_OPEN
    sta target_dir_ptr
    jsr set_target_sprite_from_cell
    rts

try_requested_down:
    jsr load_legal_mask
    and #MASK_DOWN
    beq continue_current_direction
    lda pac_cell_x
    sta target_cell_x
    lda pac_cell_y
    clc
    adc #$01
    sta target_cell_y
    lda #SPRITE_PTR_S_OPEN
    sta target_dir_ptr
    jsr set_target_sprite_from_cell
    rts

continue_current_direction:
    lda target_dir_ptr
    cmp #SPRITE_PTR_W_OPEN
    beq try_current_left
    cmp #SPRITE_PTR_E_OPEN
    beq try_current_right
    cmp #SPRITE_PTR_N_OPEN
    beq try_current_up
    cmp #SPRITE_PTR_S_OPEN
    beq try_current_down
    rts

try_current_left:
    jsr load_legal_mask
    and #MASK_LEFT
    beq stop_at_cell_center
    lda pac_cell_x
    sec
    sbc #$01
    sta target_cell_x
    lda pac_cell_y
    sta target_cell_y
    lda #SPRITE_PTR_W_OPEN
    sta target_dir_ptr
    jsr set_target_sprite_from_cell
    rts

try_current_right:
    jsr load_legal_mask
    and #MASK_RIGHT
    beq stop_at_cell_center
    lda pac_cell_x
    clc
    adc #$01
    sta target_cell_x
    lda pac_cell_y
    sta target_cell_y
    lda #SPRITE_PTR_E_OPEN
    sta target_dir_ptr
    jsr set_target_sprite_from_cell
    rts

try_current_up:
    jsr load_legal_mask
    and #MASK_UP
    beq stop_at_cell_center
    lda pac_cell_x
    sta target_cell_x
    lda pac_cell_y
    sec
    sbc #$01
    sta target_cell_y
    lda #SPRITE_PTR_N_OPEN
    sta target_dir_ptr
    jsr set_target_sprite_from_cell
    rts

try_current_down:
    jsr load_legal_mask
    and #MASK_DOWN
    beq stop_at_cell_center
    lda pac_cell_x
    sta target_cell_x
    lda pac_cell_y
    clc
    adc #$01
    sta target_cell_y
    lda #SPRITE_PTR_S_OPEN
    sta target_dir_ptr
    jsr set_target_sprite_from_cell
    rts

stop_at_cell_center:
    rts

load_legal_mask:
    ldx pac_cell_y
    lda legal_row_lo,x
    sta LEGAL_PTR
    lda legal_row_hi,x
    sta LEGAL_PTR+1
    ldy pac_cell_x
    lda (LEGAL_PTR),y
    rts

set_target_sprite_from_cell:
    ldx target_cell_x
    lda sprite_x_lo_by_cell,x
    sta target_x_lo
    lda sprite_x_hi_by_cell,x
    sta target_x_hi
    ldx target_cell_y
    lda sprite_y_by_cell,x
    sta target_y
    rts

set_sprite_pointer_current:
    lda target_dir_ptr
    ldy mouth_phase
    beq sprite_pointer_ready
    clc
    adc #$04
sprite_pointer_ready:
    sta $07f8
    rts

update_mouth_animation:
    inc mouth_counter
    lda mouth_counter
    and #$07
    bne mouth_done
    lda mouth_phase
    eor #$01
    sta mouth_phase
mouth_done:
    rts

update_sprite_registers:
    lda sprite_x_lo
    sta $d000
    lda sprite_y
    sta $d001
    lda $d010
    and #$fe
    ora sprite_x_hi
    sta $d010
    rts

at_target:
    lda sprite_x_lo
    cmp target_x_lo
    bne not_at_target
    lda sprite_x_hi
    cmp target_x_hi
    bne not_at_target
    lda sprite_y
    cmp target_y
    bne not_at_target
    lda #$01
    rts
not_at_target:
    lda #$00
    rts

move_sprite_toward_target:
    lda sprite_x_hi
    cmp target_x_hi
    bcc move_x_inc
    bne move_x_dec
    lda sprite_x_lo
    cmp target_x_lo
    bcc move_x_inc
    bne move_x_dec
    jmp move_y_check

move_x_inc:
    inc sprite_x_lo
    bne move_done
    inc sprite_x_hi
    jmp move_done

move_x_dec:
    lda sprite_x_lo
    bne move_x_dec_lo
    dec sprite_x_hi
move_x_dec_lo:
    dec sprite_x_lo
    jmp move_done

move_y_check:
    lda sprite_y
    cmp target_y
    bcc move_y_inc
    bne move_y_dec
    jmp move_done

move_y_inc:
    inc sprite_y
    jmp move_done

move_y_dec:
    dec sprite_y

move_done:
    rts

erase_current_cell:
    ldx pac_cell_y
    lda screen_addr_row_lo,x
    sta SCREEN_PTR
    lda screen_addr_row_hi,x
    sta SCREEN_PTR+1
    ldy pac_cell_x
    lda (SCREEN_PTR),y
    cmp #$11
    beq score_small_dot
    cmp #$12
    beq score_power_dot
    rts
score_small_dot:
    lda #$00
    sta (SCREEN_PTR),y
    jsr add_score_10
    rts
score_power_dot:
    lda #$00
    sta (SCREEN_PTR),y
    jsr add_score_50
    rts

install_custom_charset:
    ldx #$00
copy_charset_loop:
    lda custom_charset,x
    sta CUSTOM_CHARSET_ADDR,x
    inx
    cpx #CUSTOM_CHARSET_BYTES
    bne copy_charset_loop
    rts

install_sprite_data:
    ldx #$00
copy_sprite_page0:
    lda custom_sprites,x
    sta SPRITE_DATA_ADDR,x
    inx
    bne copy_sprite_page0

    ldx #$00
copy_sprite_page1:
    lda custom_sprites+$0100,x
    sta SPRITE_DATA_ADDR+$0100,x
    inx
    bne copy_sprite_page1
    rts

clear_screen:
    ldx #$00
clear_loop:
    lda #$00
    sta SCREEN_BASE,x
    sta SCREEN_BASE+$0100,x
    sta SCREEN_BASE+$0200,x
    sta SCREEN_BASE+$0300,x
    sta COLOR_BASE,x
    sta COLOR_BASE+$0100,x
    sta COLOR_BASE+$0200,x
    sta COLOR_BASE+$0300,x
    inx
    bne clear_loop
    rts

render_board:
    ldx #$00
render_board_row_loop:
    stx render_row_index
    lda board_render_row_lo,x
    sta BOARD_PTR
    lda board_render_row_hi,x
    sta BOARD_PTR+1
    lda screen_addr_row_lo,x
    sta SCREEN_PTR
    lda screen_addr_row_hi,x
    sta SCREEN_PTR+1
    lda color_addr_row_lo,x
    sta COLOR_PTR
    lda color_addr_row_hi,x
    sta COLOR_PTR+1
    ldy #$00
render_board_col_loop:
    lda (BOARD_PTR),y
    beq render_board_skip_cell
    sta (SCREEN_PTR),y
    cmp #$11
    bcs render_board_yellow
    lda #$06
    jmp render_board_store_color
render_board_yellow:
    lda #$07
render_board_store_color:
    sta (COLOR_PTR),y
render_board_skip_cell:
    iny
    cpy #BOARD_WIDTH
    bne render_board_col_loop
    ldx render_row_index
    inx
    cpx #BOARD_HEIGHT
    bne render_board_row_loop
    rts

pac_cell_x:
    .byte $00
pac_cell_y:
    .byte $00
target_cell_x:
    .byte $00
target_cell_y:
    .byte $00
sprite_x_lo:
    .byte $00
sprite_x_hi:
    .byte $00
sprite_y:
    .byte $00
target_x_lo:
    .byte $00
target_x_hi:
    .byte $00
target_y:
    .byte $00
target_dir_ptr:
    .byte $00
requested_dir_ptr:
    .byte $00
joystick_state:
    .byte $ff
keyboard_row_state:
    .byte $ff
render_row_index:
    .byte $00
score_digits:
    .byte $30, $30, $30, $30, $30, $30
mouth_counter:
    .byte $00
mouth_phase:
    .byte $00

; Custom character projection for board.
custom_charset:
custom_char_00:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
custom_char_01:
    .byte $00, $00, $00, $18, $18, $00, $00, $00
custom_char_02:
    .byte $18, $18, $18, $18, $18, $00, $00, $00
custom_char_03:
    .byte $00, $00, $00, $1f, $1f, $00, $00, $00
custom_char_04:
    .byte $18, $18, $18, $1f, $1f, $00, $00, $00
custom_char_05:
    .byte $00, $00, $00, $18, $18, $18, $18, $18
custom_char_06:
    .byte $18, $18, $18, $18, $18, $18, $18, $18
custom_char_07:
    .byte $00, $00, $00, $1f, $1f, $18, $18, $18
custom_char_08:
    .byte $18, $18, $18, $1f, $1f, $18, $18, $18
custom_char_09:
    .byte $00, $00, $00, $f8, $f8, $00, $00, $00
custom_char_10:
    .byte $18, $18, $18, $f8, $f8, $00, $00, $00
custom_char_11:
    .byte $00, $00, $00, $ff, $ff, $00, $00, $00
custom_char_12:
    .byte $18, $18, $18, $ff, $ff, $00, $00, $00
custom_char_13:
    .byte $00, $00, $00, $f8, $f8, $18, $18, $18
custom_char_14:
    .byte $18, $18, $18, $f8, $f8, $18, $18, $18
custom_char_15:
    .byte $00, $00, $00, $ff, $ff, $18, $18, $18
custom_char_16:
    .byte $18, $18, $18, $ff, $ff, $18, $18, $18
custom_char_17:
    .byte $00, $00, $00, $18, $18, $00, $00, $00
custom_char_18:
    .byte $00, $00, $3c, $3c, $3c, $3c, $00, $00

; Hardware sprite data for Pac-Man directions.
custom_sprites:
sprite_pacman_east_open:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $38, $00, $00, $fe, $00, $01
    .byte $ff, $00, $03, $ff, $00, $03, $fc, $00
    .byte $07, $f8, $00, $07, $f0, $00, $07, $f8
    .byte $00, $03, $fc, $00, $03, $ff, $00, $01
    .byte $ff, $00, $00, $fe, $00, $00, $38, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
sprite_pacman_west_open:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $38, $00, $00, $fe, $00, $01
    .byte $ff, $00, $01, $ff, $80, $00, $7f, $80
    .byte $00, $3f, $c0, $00, $1f, $c0, $00, $3f
    .byte $c0, $00, $7f, $80, $01, $ff, $80, $01
    .byte $ff, $00, $00, $fe, $00, $00, $38, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
sprite_pacman_north_open:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $01
    .byte $83, $00, $03, $83, $80, $03, $c7, $80
    .byte $07, $ef, $c0, $07, $ff, $c0, $07, $ff
    .byte $c0, $03, $ff, $80, $03, $ff, $80, $01
    .byte $ff, $00, $00, $fe, $00, $00, $38, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
sprite_pacman_south_open:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $38, $00, $00, $fe, $00, $01
    .byte $ff, $00, $03, $ff, $80, $03, $ff, $80
    .byte $07, $ff, $c0, $07, $ff, $c0, $07, $ef
    .byte $c0, $03, $c7, $80, $03, $83, $80, $01
    .byte $83, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
sprite_pacman_east_closed:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $38, $00, $00, $fe, $00, $01
    .byte $ff, $00, $03, $ff, $80, $03, $ff, $80
    .byte $07, $ff, $c0, $07, $ff, $c0, $07, $ff
    .byte $c0, $03, $ff, $80, $03, $ff, $80, $01
    .byte $ff, $00, $00, $fe, $00, $00, $38, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
sprite_pacman_west_closed:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $38, $00, $00, $fe, $00, $01
    .byte $ff, $00, $03, $ff, $80, $03, $ff, $80
    .byte $07, $ff, $c0, $07, $ff, $c0, $07, $ff
    .byte $c0, $03, $ff, $80, $03, $ff, $80, $01
    .byte $ff, $00, $00, $fe, $00, $00, $38, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
sprite_pacman_north_closed:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $38, $00, $00, $fe, $00, $01
    .byte $ff, $00, $03, $ff, $80, $03, $ff, $80
    .byte $07, $ff, $c0, $07, $ff, $c0, $07, $ff
    .byte $c0, $03, $ff, $80, $03, $ff, $80, $01
    .byte $ff, $00, $00, $fe, $00, $00, $38, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
sprite_pacman_south_closed:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $38, $00, $00, $fe, $00, $01
    .byte $ff, $00, $03, $ff, $80, $03, $ff, $80
    .byte $07, $ff, $c0, $07, $ff, $c0, $07, $ff
    .byte $c0, $03, $ff, $80, $03, $ff, $80, $01
    .byte $ff, $00, $00, $fe, $00, $00, $38, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00

; Compact board-render character rows generated from board.txt.
; Zero entries are skipped because clear_screen already initialized blank black cells.
board_render_rows:
board_render_row_00:
    .byte $07, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0f, $0f, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0b, $0d
board_render_row_01:
    .byte $06, $12, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $08, $0e, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $12, $06
board_render_row_02:
    .byte $06, $11, $03, $0b, $0b, $09, $11, $03, $0b, $0b, $0b, $09, $11, $04, $0a, $11, $03, $0b, $0b, $0b, $09, $11, $03, $0b, $0b, $09, $11, $06
board_render_row_03:
    .byte $06, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $06
board_render_row_04:
    .byte $06, $11, $03, $0b, $0b, $09, $11, $07, $0d, $11, $03, $0b, $0b, $0f, $0f, $0b, $0b, $09, $11, $07, $0d, $11, $03, $0b, $0b, $09, $11, $06
board_render_row_05:
    .byte $06, $11, $11, $11, $11, $11, $11, $08, $0e, $11, $11, $11, $11, $08, $0e, $11, $11, $11, $11, $08, $0e, $11, $11, $11, $11, $11, $11, $06
board_render_row_06:
    .byte $04, $0b, $0b, $0b, $0b, $0d, $11, $08, $10, $0b, $0b, $09, $00, $04, $0a, $00, $03, $0b, $0b, $10, $0e, $11, $07, $0b, $0b, $0b, $0b, $0a
board_render_row_07:
    .byte $00, $00, $00, $00, $00, $06, $11, $08, $0e, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $08, $0e, $11, $06, $00, $00, $00, $00, $00
board_render_row_08:
    .byte $03, $0b, $0b, $0b, $0b, $0a, $11, $04, $0a, $00, $07, $0b, $09, $00, $00, $03, $0b, $0d, $00, $04, $0a, $11, $04, $0b, $0b, $0b, $0b, $09
board_render_row_09:
    .byte $00, $00, $00, $00, $00, $00, $11, $00, $00, $00, $06, $00, $00, $00, $00, $00, $00, $06, $00, $00, $00, $11, $00, $00, $00, $00, $00, $00
board_render_row_10:
    .byte $03, $0b, $0b, $0b, $0b, $0d, $11, $07, $0d, $00, $04, $0b, $0b, $0b, $0b, $0b, $0b, $0a, $00, $07, $0d, $11, $07, $0b, $0b, $0b, $0b, $09
board_render_row_11:
    .byte $00, $00, $00, $00, $00, $06, $11, $08, $0e, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $08, $0e, $11, $06, $00, $00, $00, $00, $00
board_render_row_12:
    .byte $07, $0b, $0b, $0b, $0b, $0a, $11, $04, $0a, $00, $03, $0b, $0b, $0b, $0b, $0b, $0b, $09, $00, $04, $0a, $11, $04, $0b, $0b, $0b, $0b, $0d
board_render_row_13:
    .byte $06, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $00, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $06
board_render_row_14:
    .byte $06, $11, $03, $0b, $0f, $0d, $11, $03, $0b, $0b, $0b, $09, $11, $03, $09, $11, $03, $0b, $0b, $0b, $09, $11, $07, $0f, $0b, $09, $11, $06
board_render_row_15:
    .byte $06, $12, $11, $11, $08, $0e, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $08, $0e, $11, $11, $12, $06
board_render_row_16:
    .byte $08, $0b, $09, $11, $04, $0a, $11, $07, $0d, $11, $03, $0b, $0b, $0f, $0f, $0b, $0b, $09, $11, $07, $0d, $11, $04, $0a, $11, $03, $0b, $0e
board_render_row_17:
    .byte $06, $11, $11, $11, $11, $11, $11, $08, $0e, $11, $11, $11, $11, $08, $0e, $11, $11, $11, $11, $08, $0e, $11, $11, $11, $11, $11, $11, $06
board_render_row_18:
    .byte $06, $11, $03, $0b, $0b, $0b, $0b, $0c, $0c, $0b, $0b, $09, $11, $04, $0a, $11, $03, $0b, $0b, $0c, $0c, $0b, $0b, $0b, $0b, $09, $11, $06
board_render_row_19:
    .byte $06, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $11, $06
board_render_row_20:
    .byte $06, $11, $07, $0f, $0f, $0f, $0f, $0f, $0f, $0f, $0f, $0f, $0d, $11, $11, $07, $0f, $0f, $0f, $0f, $0f, $0f, $0f, $0f, $0f, $0d, $11, $06
board_render_row_21:
    .byte $04, $0b, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0b, $0b, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0b, $0a

board_render_row_lo:
    .byte <board_render_row_00, <board_render_row_01, <board_render_row_02, <board_render_row_03, <board_render_row_04, <board_render_row_05, <board_render_row_06, <board_render_row_07, <board_render_row_08, <board_render_row_09, <board_render_row_10, <board_render_row_11, <board_render_row_12, <board_render_row_13, <board_render_row_14, <board_render_row_15, <board_render_row_16, <board_render_row_17, <board_render_row_18, <board_render_row_19, <board_render_row_20, <board_render_row_21
board_render_row_hi:
    .byte >board_render_row_00, >board_render_row_01, >board_render_row_02, >board_render_row_03, >board_render_row_04, >board_render_row_05, >board_render_row_06, >board_render_row_07, >board_render_row_08, >board_render_row_09, >board_render_row_10, >board_render_row_11, >board_render_row_12, >board_render_row_13, >board_render_row_14, >board_render_row_15, >board_render_row_16, >board_render_row_17, >board_render_row_18, >board_render_row_19, >board_render_row_20, >board_render_row_21

; Joystick legality masks generated from board.txt.
; bit 0 = up, bit 1 = down, bit 2 = left, bit 3 = right
legal_move_rows:
legal_row_00:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
legal_row_01:
    .byte $00, $0a, $0c, $0c, $0c, $0c, $0e, $0c, $0c, $0c, $0c, $0c, $06, $00, $00, $0a, $0c, $0c, $0c, $0c, $0c, $0e, $0c, $0c, $0c, $0c, $06, $00
legal_row_02:
    .byte $00, $03, $00, $00, $00, $00, $03, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $03, $00, $00, $00, $00, $03, $00
legal_row_03:
    .byte $00, $0b, $0c, $0c, $0c, $0c, $0f, $0c, $0c, $0e, $0c, $0c, $0d, $0c, $0c, $0d, $0c, $0c, $0e, $0c, $0c, $0f, $0c, $0c, $0c, $0c, $07, $00
legal_row_04:
    .byte $00, $03, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $03, $00
legal_row_05:
    .byte $00, $09, $0c, $0c, $0c, $0c, $07, $00, $00, $09, $0c, $0c, $06, $00, $00, $0a, $0c, $0c, $05, $00, $00, $0b, $0c, $0c, $0c, $0c, $05, $00
legal_row_06:
    .byte $00, $00, $00, $00, $00, $00, $03, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $03, $00, $00, $00, $00, $00, $00
legal_row_07:
    .byte $00, $00, $00, $00, $00, $00, $03, $00, $00, $0a, $0c, $0c, $0d, $0e, $0e, $0d, $0c, $0c, $06, $00, $00, $03, $00, $00, $00, $00, $00, $00
legal_row_08:
    .byte $00, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $0b, $07, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $00
legal_row_09:
    .byte $08, $0c, $0c, $0c, $0c, $0c, $0f, $0c, $0c, $07, $00, $08, $0c, $0d, $0d, $0c, $04, $00, $0b, $0c, $0c, $0f, $0c, $0c, $0c, $0c, $0c, $04
legal_row_10:
    .byte $00, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $00
legal_row_11:
    .byte $00, $00, $00, $00, $00, $00, $03, $00, $00, $0b, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $07, $00, $00, $03, $00, $00, $00, $00, $00, $00
legal_row_12:
    .byte $00, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $00
legal_row_13:
    .byte $00, $0a, $0c, $0c, $0c, $0c, $0f, $0c, $0c, $0d, $0c, $0c, $0e, $0c, $0c, $0e, $0c, $0c, $0d, $0c, $0c, $0f, $0c, $0c, $0c, $0c, $06, $00
legal_row_14:
    .byte $00, $03, $00, $00, $00, $00, $03, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $03, $00, $00, $00, $00, $03, $00
legal_row_15:
    .byte $00, $09, $0c, $06, $00, $00, $0b, $0c, $0c, $0e, $0c, $0c, $0d, $0c, $0c, $0d, $0c, $0c, $0e, $0c, $0c, $07, $00, $00, $0a, $0c, $05, $00
legal_row_16:
    .byte $00, $00, $00, $03, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $03, $00, $00, $00
legal_row_17:
    .byte $00, $0a, $0c, $0d, $0c, $0c, $05, $00, $00, $09, $0c, $0c, $06, $00, $00, $0a, $0c, $0c, $05, $00, $00, $09, $0c, $0c, $0d, $0c, $06, $00
legal_row_18:
    .byte $00, $03, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $03, $00, $00, $03, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $03, $00
legal_row_19:
    .byte $00, $0b, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0d, $0e, $0e, $0d, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $0c, $07, $00
legal_row_20:
    .byte $00, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $09, $05, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00
legal_row_21:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

legal_row_lo:
    .byte <legal_row_00, <legal_row_01, <legal_row_02, <legal_row_03, <legal_row_04, <legal_row_05, <legal_row_06, <legal_row_07, <legal_row_08, <legal_row_09, <legal_row_10, <legal_row_11, <legal_row_12, <legal_row_13, <legal_row_14, <legal_row_15, <legal_row_16, <legal_row_17, <legal_row_18, <legal_row_19, <legal_row_20, <legal_row_21
legal_row_hi:
    .byte >legal_row_00, >legal_row_01, >legal_row_02, >legal_row_03, >legal_row_04, >legal_row_05, >legal_row_06, >legal_row_07, >legal_row_08, >legal_row_09, >legal_row_10, >legal_row_11, >legal_row_12, >legal_row_13, >legal_row_14, >legal_row_15, >legal_row_16, >legal_row_17, >legal_row_18, >legal_row_19, >legal_row_20, >legal_row_21

; Screen and color row base addresses for compact rendering and dot clearing.
screen_addr_row_lo:
    .byte $2e, $56, $7e, $a6, $ce, $f6, $1e, $46, $6e, $96, $be, $e6, $0e, $36, $5e, $86, $ae, $d6, $fe, $26, $4e, $76
screen_addr_row_hi:
    .byte $04, $04, $04, $04, $04, $04, $05, $05, $05, $05, $05, $05, $06, $06, $06, $06, $06, $06, $06, $07, $07, $07
color_addr_row_lo:
    .byte $2e, $56, $7e, $a6, $ce, $f6, $1e, $46, $6e, $96, $be, $e6, $0e, $36, $5e, $86, $ae, $d6, $fe, $26, $4e, $76
color_addr_row_hi:
    .byte $d8, $d8, $d8, $d8, $d8, $d8, $d9, $d9, $d9, $d9, $d9, $d9, $da, $da, $da, $da, $da, $da, $da, $db, $db, $db

; Sprite coordinate projection tables.
sprite_x_lo_by_cell:
    .byte $41, $49, $51, $59, $61, $69, $71, $79, $81, $89, $91, $99, $a1, $a9, $b1, $b9, $c1, $c9, $d1, $d9, $e1, $e9, $f1, $f9, $01, $09, $11, $19
sprite_x_hi_by_cell:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $01, $01, $01
sprite_y_by_cell:
    .byte $34, $3c, $44, $4c, $54, $5c, $64, $6c, $74, $7c, $84, $8c, $94, $9c, $a4, $ac, $b4, $bc, $c4, $cc, $d4, $dc

; Board text audit authority remains in src/board.txt and src/projected_board.json.
; Runtime board rendering uses compact board_render_row_* tables above.
