; Generated by labs/010_goal_language_to_asm_pacman_bounce/src/generate_asm.py
; Goal source: labs/010_goal_language_to_asm_pacman_bounce/src/goal.lang
; Program source: labs/010_goal_language_to_asm_pacman_bounce/src/program.lang
; Goal: PACMAN BOUNCE
; Priority: runtime speed first; teaching clarity is secondary.
; Output: assembly app source. No main.c is generated or consumed.
; Motion: signed dx_vel/dy_vel vector; edge bounce reflects only the hit axis.
; Mouth: direction_from_vector(dx_vel, dy_vel) selects E NE N NW W SW S SE.
; Guardrail: left/right-only mouth selection is forbidden.
.import __EXEHDR__
.export _main

SCREEN_RAM = $0400
COLOR_RAM = $d800
SPACE_CHAR = $20
SPRITE_POINTER_0 = $07f8
SPRITE_DATA = $2000
SPRITE_DATA_CLOSED = $2000
SPRITE_DATA_POINTER_CLOSED = $80
SPRITE_DATA_OPEN_E = $2040
SPRITE_DATA_POINTER_OPEN_E = $81
SPRITE_DATA_OPEN_NE = $2080
SPRITE_DATA_POINTER_OPEN_NE = $82
SPRITE_DATA_OPEN_N = $20c0
SPRITE_DATA_POINTER_OPEN_N = $83
SPRITE_DATA_OPEN_NW = $2100
SPRITE_DATA_POINTER_OPEN_NW = $84
SPRITE_DATA_OPEN_W = $2140
SPRITE_DATA_POINTER_OPEN_W = $85
SPRITE_DATA_OPEN_SW = $2180
SPRITE_DATA_POINTER_OPEN_SW = $86
SPRITE_DATA_OPEN_S = $21c0
SPRITE_DATA_POINTER_OPEN_S = $87
SPRITE_DATA_OPEN_SE = $2200
SPRITE_DATA_POINTER_OPEN_SE = $88
VIC_SPRITE0_X = $d000
VIC_SPRITE0_Y = $d001
SPRITE_X_MSB = $d010
SPRITE_ENABLE = $d015
RASTER = $d012
SPRITE0_COLOR = $d027
BORDER_COLOR = $d020
BACKGROUND_COLOR = $d021
MIN_X = $18
MAX_X = $e8
MIN_Y = $32
MAX_Y = $e5
DX_POS = $02
DX_NEG = $fe
DY_POS = $01
DY_NEG = $ff

.segment "STARTUP"
_main:
    ; speed-first generated setup from goal/program language
    lda #$00
    sta BORDER_COLOR
    lda #$00
    sta BACKGROUND_COLOR
    ; exact 1000-byte clear: four 250-byte stripes, no overlap
    ldy #250
fast_clear_loop_01:
    lda #SPACE_CHAR
    sta SCREEN_RAM-1,y
    sta SCREEN_RAM+249,y
    sta SCREEN_RAM+499,y
    sta SCREEN_RAM+749,y
    lda #$00
    sta COLOR_RAM-1,y
    sta COLOR_RAM+249,y
    sta COLOR_RAM+499,y
    sta COLOR_RAM+749,y
    dey
    bne fast_clear_loop_01

    ; copy generated closed and eight vector-facing open-mouth frames
    ldx #$3f
copy_pacman_sprite_01:
    lda pacman_sprite_closed_data,x
    sta SPRITE_DATA_CLOSED,x
    lda pacman_sprite_open_e_data,x
    sta SPRITE_DATA_OPEN_E,x
    lda pacman_sprite_open_ne_data,x
    sta SPRITE_DATA_OPEN_NE,x
    lda pacman_sprite_open_n_data,x
    sta SPRITE_DATA_OPEN_N,x
    lda pacman_sprite_open_nw_data,x
    sta SPRITE_DATA_OPEN_NW,x
    lda pacman_sprite_open_w_data,x
    sta SPRITE_DATA_OPEN_W,x
    lda pacman_sprite_open_sw_data,x
    sta SPRITE_DATA_OPEN_SW,x
    lda pacman_sprite_open_s_data,x
    sta SPRITE_DATA_OPEN_S,x
    lda pacman_sprite_open_se_data,x
    sta SPRITE_DATA_OPEN_SE,x
    dex
    bpl copy_pacman_sprite_01

    ; color and enable sprite 0
    lda #$07
    sta SPRITE0_COLOR
    lda #$01
    sta SPRITE_ENABLE
    lda #$00
    sta SPRITE_X_MSB

    lda #$78
    sta x_pos
    lda #$64
    sta y_pos
    lda #$02
    sta dx_vel
    lda #$01
    sta dy_vel
    lda #$00
    sta mouth_timer
    sta mouth_state
    jsr update_mouth_pointer_01
    jsr update_sprite_01

main_loop_01:
    jsr wait_frame_01

    ; x = x + dx; reflect at left/right boundaries
    lda x_pos
    clc
    adc dx_vel
    sta x_pos
    cmp #MIN_X
    bcs check_right_edge_01
hit_left_edge_01:
    lda #MIN_X
    sta x_pos
    lda #DX_POS
    sta dx_vel
    jmp update_y_01
check_right_edge_01:
    cmp #MAX_X
    bcc update_y_01
hit_right_edge_01:
    lda #MAX_X
    sta x_pos
    lda #DX_NEG
    sta dx_vel

update_y_01:
    ; y = y + dy; reflect at top/bottom boundaries
    lda y_pos
    clc
    adc dy_vel
    sta y_pos
    cmp #MIN_Y
    bcs check_bottom_edge_01
hit_top_edge_01:
    lda #MIN_Y
    sta y_pos
    lda #DY_POS
    sta dy_vel
    jmp draw_sprite_01
check_bottom_edge_01:
    cmp #MAX_Y
    bcc draw_sprite_01
hit_bottom_edge_01:
    lda #MAX_Y
    sta y_pos
    lda #DY_NEG
    sta dy_vel

draw_sprite_01:
    jsr animate_mouth_01
    jsr update_mouth_pointer_01
    jsr update_sprite_01
    jmp main_loop_01

animate_mouth_01:
    inc mouth_timer
    lda mouth_timer
    and #$07
    bne mouth_done_01
    lda mouth_state
    eor #$01
    sta mouth_state
mouth_done_01:
    rts

update_mouth_pointer_01:
    ; closed mouth is neutral; open mouth faces direction_from_vector(dx_vel, dy_vel)
    lda mouth_state
    bne mouth_closed_01
    lda dy_vel
    beq mouth_vector_horizontal_01
    bmi mouth_vector_north_01
mouth_vector_south_01:
    lda dx_vel
    beq mouth_open_s_01
    bmi mouth_open_sw_01
    jmp mouth_open_se_01
mouth_vector_north_01:
    lda dx_vel
    beq mouth_open_n_01
    bmi mouth_open_nw_01
    jmp mouth_open_ne_01
mouth_vector_horizontal_01:
    lda dx_vel
    bmi mouth_open_w_01
mouth_open_e_01:
    lda #SPRITE_DATA_POINTER_OPEN_E
    sta SPRITE_POINTER_0
    rts
mouth_open_ne_01:
    lda #SPRITE_DATA_POINTER_OPEN_NE
    sta SPRITE_POINTER_0
    rts
mouth_open_n_01:
    lda #SPRITE_DATA_POINTER_OPEN_N
    sta SPRITE_POINTER_0
    rts
mouth_open_nw_01:
    lda #SPRITE_DATA_POINTER_OPEN_NW
    sta SPRITE_POINTER_0
    rts
mouth_open_w_01:
    lda #SPRITE_DATA_POINTER_OPEN_W
    sta SPRITE_POINTER_0
    rts
mouth_open_sw_01:
    lda #SPRITE_DATA_POINTER_OPEN_SW
    sta SPRITE_POINTER_0
    rts
mouth_open_s_01:
    lda #SPRITE_DATA_POINTER_OPEN_S
    sta SPRITE_POINTER_0
    rts
mouth_open_se_01:
    lda #SPRITE_DATA_POINTER_OPEN_SE
    sta SPRITE_POINTER_0
    rts
mouth_closed_01:
    lda #SPRITE_DATA_POINTER_CLOSED
    sta SPRITE_POINTER_0
    rts

update_sprite_01:
    lda x_pos
    sta VIC_SPRITE0_X
    lda y_pos
    sta VIC_SPRITE0_Y
    rts

wait_frame_01:
    lda #$f8
wait_raster_01:
    cmp RASTER
    bne wait_raster_01
wait_raster_leave_01:
    lda RASTER
    cmp #$f8
    beq wait_raster_leave_01
    rts

x_pos:
    .byte $78
y_pos:
    .byte $64
dx_vel:
    .byte $02
dy_vel:
    .byte $01
mouth_timer:
    .byte $00
mouth_state:
    .byte $00

pacman_sprite_closed_data:
    .byte $00, $00, $00, $00, $ff, $00, $03, $ff
    .byte $c0, $07, $ff, $e0, $0f, $ff, $f0, $1f
    .byte $ff, $f8, $3f, $ff, $fc, $3f, $ff, $fc
    .byte $3f, $ff, $fc, $3f, $ff, $fc, $7f, $ff
    .byte $fe, $3f, $ff, $fc, $3f, $ff, $fc, $3f
    .byte $ff, $fc, $3f, $ff, $fc, $1f, $ff, $f8
    .byte $0f, $ff, $f0, $07, $ff, $e0, $03, $ff
    .byte $c0, $00, $ff, $00, $00, $00, $00, $00
pacman_sprite_open_e_data:
    .byte $00, $00, $00, $00, $ff, $00, $03, $ff
    .byte $c0, $07, $ff, $e0, $0f, $ff, $f0, $1f
    .byte $ff, $f8, $3f, $ff, $f0, $3f, $ff, $c0
    .byte $3f, $ff, $00, $3f, $fc, $00, $7f, $f8
    .byte $00, $3f, $fc, $00, $3f, $ff, $00, $3f
    .byte $ff, $c0, $3f, $ff, $f0, $1f, $ff, $f8
    .byte $0f, $ff, $f0, $07, $ff, $e0, $03, $ff
    .byte $c0, $00, $ff, $00, $00, $00, $00, $00
pacman_sprite_open_ne_data:
    .byte $00, $00, $00, $00, $fe, $00, $03, $fe
    .byte $00, $07, $fc, $00, $0f, $fc, $00, $1f
    .byte $fc, $00, $3f, $f8, $00, $3f, $f8, $04
    .byte $3f, $f8, $3c, $3f, $f1, $fc, $7f, $ff
    .byte $fe, $3f, $ff, $fc, $3f, $ff, $fc, $3f
    .byte $ff, $fc, $3f, $ff, $fc, $1f, $ff, $f8
    .byte $0f, $ff, $f0, $07, $ff, $e0, $03, $ff
    .byte $c0, $00, $ff, $00, $00, $00, $00, $00
pacman_sprite_open_n_data:
    .byte $00, $00, $00, $00, $00, $00, $03, $00
    .byte $c0, $07, $81, $e0, $0f, $81, $f0, $1f
    .byte $c3, $f8, $3f, $c3, $fc, $3f, $e7, $fc
    .byte $3f, $e7, $fc, $3f, $ff, $fc, $7f, $ff
    .byte $fe, $3f, $ff, $fc, $3f, $ff, $fc, $3f
    .byte $ff, $fc, $3f, $ff, $fc, $1f, $ff, $f8
    .byte $0f, $ff, $f0, $07, $ff, $e0, $03, $ff
    .byte $c0, $00, $ff, $00, $00, $00, $00, $00
pacman_sprite_open_nw_data:
    .byte $00, $00, $00, $00, $7f, $00, $00, $7f
    .byte $c0, $00, $3f, $e0, $00, $3f, $f0, $00
    .byte $3f, $f8, $00, $1f, $fc, $20, $1f, $fc
    .byte $3c, $1f, $fc, $3f, $8f, $fc, $7f, $ff
    .byte $fe, $3f, $ff, $fc, $3f, $ff, $fc, $3f
    .byte $ff, $fc, $3f, $ff, $fc, $1f, $ff, $f8
    .byte $0f, $ff, $f0, $07, $ff, $e0, $03, $ff
    .byte $c0, $00, $ff, $00, $00, $00, $00, $00
pacman_sprite_open_w_data:
    .byte $00, $00, $00, $00, $ff, $00, $03, $ff
    .byte $c0, $07, $ff, $e0, $0f, $ff, $f0, $1f
    .byte $ff, $f8, $0f, $ff, $fc, $03, $ff, $fc
    .byte $00, $ff, $fc, $00, $3f, $fc, $00, $1f
    .byte $fe, $00, $3f, $fc, $00, $ff, $fc, $03
    .byte $ff, $fc, $0f, $ff, $fc, $1f, $ff, $f8
    .byte $0f, $ff, $f0, $07, $ff, $e0, $03, $ff
    .byte $c0, $00, $ff, $00, $00, $00, $00, $00
pacman_sprite_open_sw_data:
    .byte $00, $00, $00, $00, $ff, $00, $03, $ff
    .byte $c0, $07, $ff, $e0, $0f, $ff, $f0, $1f
    .byte $ff, $f8, $3f, $ff, $fc, $3f, $ff, $fc
    .byte $3f, $ff, $fc, $3f, $ff, $fc, $7f, $ff
    .byte $fe, $3f, $8f, $fc, $3c, $1f, $fc, $20
    .byte $1f, $fc, $00, $1f, $fc, $00, $3f, $f8
    .byte $00, $3f, $f0, $00, $3f, $e0, $00, $7f
    .byte $c0, $00, $7f, $00, $00, $00, $00, $00
pacman_sprite_open_s_data:
    .byte $00, $00, $00, $00, $ff, $00, $03, $ff
    .byte $c0, $07, $ff, $e0, $0f, $ff, $f0, $1f
    .byte $ff, $f8, $3f, $ff, $fc, $3f, $ff, $fc
    .byte $3f, $ff, $fc, $3f, $ff, $fc, $7f, $ff
    .byte $fe, $3f, $ff, $fc, $3f, $e7, $fc, $3f
    .byte $e7, $fc, $3f, $c3, $fc, $1f, $c3, $f8
    .byte $0f, $81, $f0, $07, $81, $e0, $03, $00
    .byte $c0, $00, $00, $00, $00, $00, $00, $00
pacman_sprite_open_se_data:
    .byte $00, $00, $00, $00, $ff, $00, $03, $ff
    .byte $c0, $07, $ff, $e0, $0f, $ff, $f0, $1f
    .byte $ff, $f8, $3f, $ff, $fc, $3f, $ff, $fc
    .byte $3f, $ff, $fc, $3f, $ff, $fc, $7f, $ff
    .byte $fe, $3f, $f1, $fc, $3f, $f8, $3c, $3f
    .byte $f8, $04, $3f, $f8, $00, $1f, $fc, $00
    .byte $0f, $fc, $00, $07, $fc, $00, $03, $fe
    .byte $00, $00, $fe, $00, $00, $00, $00, $00

.segment "INIT"
.segment "ONCE"
.segment "CODE"
