from pathlib import Path
import json
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]

REQUIRED = {
    "li/domain/language_to_assembly_contract.md": ["language command text", "parsed intent model", "generated assembly", "Unknown commands must fail closed"],
    "docs/c64/language_to_assembly_layer.md": ["Lab 009", "program.lang", "generated_intent.json", "generated.s"],
    "prompts/c64_build_language_to_asm_lab.md": ["controlled language", "deterministic", "fail closed"],
    "prompts/c64_language_to_asm_capture_back.md": ["program.lang", "generated_intent.json", "generated.s"],
    "captures/CAPTURE_BACK_C64_LANGUAGE_TO_ASM_LI.md": ["language-to-assembly", "program.lang"],
    "cards/015_c64_language_to_asm_li_card.md": ["Language-to-Assembly", "repo-owned generator"],
    "labs/009_language_to_asm/README.md": ["Language to Assembly", "program.lang", "generated_intent.json", "generated.s"],
    "labs/009_language_to_asm/expected.md": ["LANGUAGE TO ASM", "GENERATED 6502"],
    "labs/009_language_to_asm/Makefile": ["generate_asm.py", "generated_intent.json", "generated.s", "cl65 -t c64"],
    "labs/009_language_to_asm/src/program.lang": ["set border blue", "put \"LANGUAGE TO ASM\""],
    "labs/009_language_to_asm/src/generate_asm.py": ["Unknown commands", "screen_code", "emit_asm", "__EXEHDR__", "STARTUP"],
    "labs/009_language_to_asm/src/generated_intent.json": ["put_text", "LANGUAGE TO ASM"],
    "labs/009_language_to_asm/src/generated.s": ["Generated by", "sta $d020", "LANGUAGE TO ASM", "__EXEHDR__", ".segment \"STARTUP\""],
}

errors = []
for rel, needles in REQUIRED.items():
    path = ROOT / rel
    if not path.exists():
        errors.append(f"missing {rel}")
        continue
    text = path.read_text(errors="ignore")
    for needle in needles:
        if needle not in text:
            errors.append(f"{rel} missing token {needle!r}")

makefile = (ROOT / "Makefile").read_text(errors="ignore") if (ROOT / "Makefile").exists() else ""
for token in ["verify-language-to-asm", "lab009", "lab009-run", "tools/verify_c64_language_to_asm.py"]:
    if token not in makefile:
        errors.append(f"Makefile missing {token}")

sequence = (ROOT / "docs/c64/lab_sequence.md").read_text(errors="ignore") if (ROOT / "docs/c64/lab_sequence.md").exists() else ""
if "Lab 009: Language to Assembly" not in sequence:
    errors.append("docs/c64/lab_sequence.md missing Lab 009 language-to-assembly entry")

try:
    intent = json.loads((ROOT / "labs/009_language_to_asm/src/generated_intent.json").read_text())
    if not any(item.get("op") == "put_text" and item.get("text") == "LANGUAGE TO ASM" for item in intent):
        errors.append("generated_intent.json missing LANGUAGE TO ASM put_text intent")
except Exception as exc:
    errors.append(f"generated_intent.json is not valid intent JSON: {exc}")

# Re-run the generator to verify deterministic regeneration.
lab = ROOT / "labs/009_language_to_asm"
try:
    subprocess.run(
        [sys.executable, "src/generate_asm.py", "src/program.lang", "src/generated_intent.json", "src/generated.s"],
        cwd=lab,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
except Exception as exc:
    errors.append(f"language-to-asm generator failed: {exc}")

if errors:
    print("C64 language-to-assembly verification failed:")
    for err in errors:
        print(f"- {err}")
    sys.exit(1)

print("OK: C64 Language-to-Assembly LI and Lab 009 custody chain are present.")
